/* Shared local experience engine. Production mutations must run on a trusted server. */
(function(root,factory){if(typeof module==='object')module.exports=factory();else root.Echo=factory()})(this,function(){
const tracks=[{id:'t1',name:'林间来信',artist:'回音森林 · 原创合成',src:'ambient1.wav',mood:'放松'},{id:'t2',name:'慢慢回家',artist:'回音森林 · 原创合成',src:'ambient2.wav',mood:'独处'},{id:'t3',name:'水面上的月亮',artist:'回音森林 · 原创合成',src:'ambient3.wav',mood:'治愈'},{id:'t4',name:'雨停以后',artist:'回音森林 · 原创合成',src:'ambient1.wav',mood:'治愈'},{id:'t5',name:'下一站，晴天',artist:'回音森林 · 原创合成',src:'ambient2.wav',mood:'散步'}];
const people={me:'林间旅人',yu:'小屿',lu:'鹿眠'};
function initial(){return {version:1,user:'me',wallets:{me:{notes:5,points:0,claimed:''},yu:{notes:5,points:0,claimed:''},lu:{notes:5,points:0,claimed:''}},posts:[{id:'p4',owner:'lu',mode:'普通',title:'借一片月光给你',message:'把声音放轻一点，今晚允许自己什么也不想。',tags:['电子','氛围','夜晚'],tracks:['t3','t1'],story:'',clue:'',created:4},{id:'p1',owner:'yu',mode:'普通',title:'把今天，调成慢速',message:'适合一个人走回家的时候听。风会替你接住那些没说完的话。',tags:['氛围','放松','散步'],tracks:['t1','t2','t3'],story:'',clue:'',created:1},{id:'p2',owner:'lu',mode:'故事',title:'那天，我们错过了末班车',message:'有些绕远的路，后来成了最想念的风景。',tags:['氛围','治愈','夜晚'],tracks:['t2','t3','t4'],story:'那天加班很晚，我和朋友错过了末班车。我们沿河走了三站路。第一首是离开车站时的安静，第二首是河面月光的样子，第三首是天快亮时终于放松的心情。',clue:'一条河、三站路，还有一次不着急的告别。',created:2},{id:'p3',owner:'yu',mode:'普通',title:'雨停了，再出发吧',message:'送给今天不太开心的人。等雨停，也等自己慢慢晴朗。',tags:['轻音乐','治愈','独处'],tracks:['t3','t4'],story:'',clue:'',created:3}],favorites:[],comments:[],likes:[],gifts:[],threads:[],redemptions:[],stock:{r1:2,r2:0}}}
function create(adapter){let state;try{state=adapter.load()}catch(e){} if(!state||state.version!==1)state=initial();
if(!state.posts.some(p=>p.id==='p4'))state.posts.push(initial().posts.find(p=>p.id==='p4'));
const genres={p1:'民谣',p2:'电子',p3:'摇滚'};state.posts.forEach(p=>{if(genres[p.id]&&!p.tags.includes(genres[p.id]))p.tags.push(genres[p.id])});
function save(){adapter.save(state)}
function requirePost(id){const p=state.posts.find(p=>p.id===id);if(!p)throw Error('这份歌单不存在');return p}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
const api={get state(){return state},tracks,people,
 user(){return state.user},wallet(){return state.wallets[state.user]},name(id){return (state.profiles||{})[id]||people[id]||'林间旅人'},
 switchUser(id){if(!people[id])throw Error('账号不存在');state.user=id;save()},
 list(filters){filters=filters||{};return state.posts.filter(p=>(!filters.mode||p.mode===filters.mode)&&(!filters.tag||p.tags.includes(filters.tag))&&(!filters.genre||p.tags.includes(filters.genre))&&(!filters.query||(p.title+p.message+p.tags.join('')+p.tracks.map(id=>api.track(id).name).join('')).includes(filters.query)))},
 post:requirePost,track(id){return tracks.find(t=>t.id===id)},
 favorite(id){requirePost(id);const i=state.favorites.findIndex(f=>f.user===state.user&&f.post===id);if(i<0)state.favorites.push({user:state.user,post:id});else state.favorites.splice(i,1);save();return i<0},
 isFavorite(id){return state.favorites.some(f=>f.user===state.user&&f.post===id)},
 comment(id,text){requirePost(id);text=text.trim();if(!text||text.length>120)throw Error('请写下 1—120 字的听后感受');state.comments.push({id:uid(),user:state.user,post:id,text});save()},
 like(id,track){const p=requirePost(id);if(!p.tracks.includes(track))throw Error('请选择歌单中的歌曲');state.likes=state.likes.filter(l=>!(l.user===state.user&&l.post===id));state.likes.push({user:state.user,post:id,track});save()},
 claim(){const d=new Date(Date.now()+8*3600000);const day=[d.getUTCFullYear(),d.getUTCMonth()+1,d.getUTCDate()].join('-');const w=api.wallet();if(w.claimed===day)throw Error('今天已经领取过了，明天再来');w.notes+=5;w.claimed=day;save()},
 gift(id){const p=requirePost(id);if(p.owner===state.user)throw Error('不能给自己的歌单赠送音符');const n=state.gifts.filter(g=>g.user===state.user&&g.post===id).length;if(n>=3)throw Error('每人对同一歌单最多赠送 3 个音符');if(api.wallet().notes<1)throw Error('音符不足，可以免费领取或留下短评');api.wallet().notes--;state.wallets[p.owner].points++;state.gifts.push({id:uid(),user:state.user,post:id,to:p.owner});save()},
 publish(d){const ts=[...new Set(d.tracks||[])];if(!ts.length||ts.some(id=>!api.track(id)))throw Error('至少选择一首曲库内的歌');if(!['普通','故事'].includes(d.mode))throw Error('请选择分享模式');if(d.mode==='故事'&&(ts.length<3||ts.length>5))throw Error('故事歌单需要 3—5 首歌');if(!(d.message||'').trim())throw Error('留一句话，让音乐有个来处');if(d.mode==='故事'&&!(d.story||'').trim())throw Error('请写下经历与歌曲的关联');if((d.title||'').length>30||(d.message||'').length>120||(d.story||'').length>1500)throw Error('内容超过长度限制');const p={id:uid(),owner:state.user,mode:d.mode,title:(d.title||'').trim()||'给路过的你',message:d.message.trim(),tags:d.tags&&d.tags.length?d.tags:['氛围'],tracks:ts,story:(d.story||'').trim(),clue:(d.clue||'').trim()||'听完这几首歌，再揭晓这段故事。',created:Date.now()};state.posts.unshift(p);save();return p},
 respond(id,track,text){const p=requirePost(id);if(p.owner===state.user)throw Error('不能给自己回赠');if(!api.track(track)||!text.trim()||text.length>120)throw Error('选一首歌，并写下 1—120 字回应');if(state.threads.some(t=>t.post===id&&t.members.includes(state.user)))throw Error('你们已有回赠记录，请到「我的回音」继续');const t={id:uid(),post:id,members:[state.user,p.owner],status:'pending',cards:[{user:state.user,track,text:text.trim()}]};state.threads.unshift(t);save();return t},
 reply(id,track,text){const t=state.threads.find(t=>t.id===id);if(!t||!t.members.includes(state.user))throw Error('会话不存在');if(t.cards[t.cards.length-1].user===state.user)throw Error('这一首已经送出，等对方接下一首吧');if(!api.track(track)||!text.trim()||text.length>120)throw Error('选一首歌，并写下 1—120 字回应');t.cards.push({user:state.user,track,text:text.trim()});t.status='active';save()},
 redeem(id){const reward=api.rewards.find(r=>r.id===id);if(!reward)throw Error('奖品不存在');if(!state.stock[id])throw Error('这份奖品暂时缺货');if(api.wallet().points<reward.cost)throw Error('奖励积分不足，继续分享好音乐吧');api.wallet().points-=reward.cost;state.stock[id]--;state.redemptions.unshift({id:uid(),user:state.user,reward:reward.name,cost:reward.cost,status:'体验记录 · 不发货',date:new Date().toLocaleDateString()});save()},
 seedShowcase(){if(state.showcaseV2)return;state.showcaseV2=true;const demo={id:'demo-own-1',owner:'me',mode:'普通',title:'把晚风留在这首歌里',message:'这首歌陪我走过了很多个睡不着的夜晚，希望也能陪伴你。',tags:['民谣','治愈','夜晚'],tracks:['t2','t3'],story:'',clue:'',created:5};state.posts.push(demo);state.threads.push({id:'demo-pending',post:demo.id,members:['yu','me'],status:'pending',cards:[{user:'yu',track:'t1',text:'捞到你的歌，想用这首回应你。也许我们会有相似的夜晚。'}]},{id:'demo-duet',post:demo.id,members:['lu','me'],status:'active',cards:[{user:'me',track:'t1',text:'像下雨时还在赶路。'},{user:'lu',track:'t2',text:'找个亮着灯的地方坐一下。'},{user:'me',track:'t3',text:'雨停了，我们继续走。'},{user:'lu',track:'t4',text:'下次，一起听海吧。'}]});save()},
 rewards:[{id:'r1',name:'森林来信 · 纸质明信片',cost:5,icon:'✉'},{id:'r2',name:'回音森林 · 帆布袋',cost:30,icon:'♧'}],
 feedback(){const ids=state.posts.filter(p=>p.owner===state.user).map(p=>p.id);return [...state.comments.filter(c=>ids.includes(c.post)).map(c=>({text:api.name(c.user)+'：'+c.text,post:c.post})),...state.gifts.filter(g=>g.to===state.user).map(g=>({text:api.name(g.user)+' 赠送了 1 个音符',post:g.post}))]},
};return api}
return {create,tracks,people,initial};
});
